[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_3C:DC:75:62:B5:D0-if00
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_3C:DC:75:62:B5:D0-if00

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.flash_mode = qio

board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1